config/routes.rb
Rails.application.routes.draw do
  resources :programs

  get 'welcome/index'
  post 'programs/:id/like' => 'programs#like', as: :like_program
  post 'programs/:id/dislike' => 'programs#dislike', as: :dislike_program

  devise_for :users
  

  root 'welcome#index'

end

app/models/program.rb
class Program < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  recommends :programs
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  protected
    def authenticate_user!
      if user_signed_in?
        super
      else
        redirect_to new_user_session_path, :notice => 'You need to login!'
        ## if you want render 404 page
        ## render :file => File.join(Rails.root, 'public/404'), :formats => [:html], :status => 404, :layout => false
      end
    end

end

app/controllers/programs_controller.rb
class ProgramsController < ApplicationController
  before_action :set_program, only: [:show, :edit, :update, :destroy, :like, :dislike]
  before_action :authenticate_user!

  # GET /programs
  # GET /programs.json
  def index
    @programs = Program.all
  end

  # GET /programs/1
  # GET /programs/1.json
  def show
  end

  # GET /programs/new
  def new
    @program = Program.new
  end

  # GET /programs/1/edit
  def edit
  end

  # POST /programs
  # POST /programs.json
  def create
    @program = Program.new(program_params)

    respond_to do |format|
      if @program.save
        format.html { redirect_to @program, notice: 'Program was successfully created.' }
        format.json { render :show, status: :created, location: @program }
      else
        format.html { render :new }
        format.json { render json: @program.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /programs/1
  # PATCH/PUT /programs/1.json
  def update
    respond_to do |format|
      if @program.update(program_params)
        format.html { redirect_to @program, notice: 'Program was successfully updated.' }
        format.json { render :show, status: :ok, location: @program }
      else
        format.html { render :edit }
        format.json { render json: @program.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /programs/1
  # DELETE /programs/1.json
  def destroy
    @program.destroy
    respond_to do |format|
      format.html { redirect_to programs_url, notice: 'Program was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  # LIKE
  def like
    current_user.like(@program)
    head :ok
  end

  # DISLIKE
  def dislike
    current_user.dislike(@program)
    head :ok
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_program
      @program = Program.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def program_params
      params.require(:program).permit(:title, :cover)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

  before_filter :authenticate_user!
  
  def index
    @programs = Program.all
    @liked    = current_user.liked_programs
    @disliked = current_user.disliked_programs
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/programs_helper.rb
module ProgramsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>DevSkrinrCom</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= stylesheet_link_tag '//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css' %>
  <%= javascript_include_tag '//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/js/bootstrap.min.js' %>
  <%= csrf_meta_tags %>
</head>
<body>

<div class="container">

      <!-- Static navbar -->
      <div class="navbar navbar-default" role="navigation">
        <div class="container-fluid">
          <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target=".navbar-collapse">
              <span class="sr-only">Toggle navigation</span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="#">Project name</a>
          </div>
          <div class="navbar-collapse collapse">
            <ul class="nav navbar-nav navbar-right">
              <% if current_user %>
              <li class="active"><a href="./">Hi, <%= current_user.email %></a></li>
              <li><%= link_to "Log out", destroy_user_session_path, :method => :delete %></li>
              <% else %>
              <li><%= link_to "Log in", new_user_session_path %></li>
              <% end %>
            </ul>
          </div><!--/.nav-collapse -->
        </div><!--/.container-fluid -->
      </div>

      <!-- Main component for a primary marketing message or call to action -->
      <% if notice %>
      <div class="alert alert-info" role="alert"><%= notice %></div>        
      <% end %>
      <% if alert %>
      <div class="alert alert-warning" role="alert"><%= alert %></div>
      <% end %>

      <div class="">
        <%= yield %>
      </div>

    </div>


</body>
</html>

app/views/programs/_form.html.erb
<%= form_for(@program) do |f| %>
  <% if @program.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@program.errors.count, "error") %> prohibited this program from being saved:</h2>

      <ul>
      <% @program.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :cover %><br>
    <%= f.text_field :cover %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/programs/edit.html.erb
<h1>Editing program</h1>

<%= render 'form' %>

<%= link_to 'Show', @program %> |
<%= link_to 'Back', programs_path %>

app/views/programs/index.html.erb
<h1>Listing programs</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Cover</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @programs.each do |program| %>
      <tr>
        <td><%= program.title %></td>
        <td><%= program.cover %></td>
        <td><%= link_to 'Show', program %></td>
        <td><%= link_to 'Edit', edit_program_path(program) %></td>
        <td><%= link_to 'Destroy', program, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Program', new_program_path %>

app/views/programs/new.html.erb
<h1>New program</h1>

<%= render 'form' %>

<%= link_to 'Back', programs_path %>

app/views/programs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @program.title %>
</p>

<p>
  <strong>Cover:</strong>
  <%= @program.cover %>
</p>

<%= link_to 'Edit', edit_program_path(@program) %> |
<%= link_to 'Back', programs_path %>

app/views/welcome/index.html.erb
<div class="row program_list liked">
  <% @liked.each do |p| %>
  <div class="col-md-2">
    <img src="<%= p.cover %>" class="img-responsive img-thumbnail" title="<%= p.title %>" data-toggle="tooltip" data-placement="bottom">
    <p>
      <%= p.id %>
    </p>
  </div>
  <% end %>
</div>
<hr />
<div class="row program_list disliked">
  <% @disliked.each do |p| %>
  <div class="col-md-2">
    <img src="<%= p.cover %>" class="img-responsive img-thumbnail" title="<%= p.title %>" data-toggle="tooltip" data-placement="bottom">
    <p>
      <%= p.id %>
    </p>
  </div>
  <% end %>
</div>
<hr />
<div class="row program_list" id="program_list">
  <% @programs.each do |p| %>
  <div class="col-md-2">
    <img src="<%= p.cover %>" class="img-responsive img-thumbnail" title="<%= p.title %>" data-toggle="tooltip" data-placement="bottom">
    <p>
      <%= p.id %><br />
      <% if current_user %>
      <a href="#" data-url="<%= dislike_program_path(p.id) %>" class="rate_btn dislike_btn">Dislike</a> |
      <a href="#" data-url="<%= like_program_path(p.id) %>" class="rate_btn like_btn">Like</a>
      <% end %>
    </p>
  </div>
  <% end %>
</div>  

<script type="text/javascript">
  
  $('#program_list img').tooltip({'placement': 'top'})
  
  function rateProgram(dataurl) {
    $.ajax({
      type: "POST",
      url: dataurl,
      beforeSend: function(xhr) {xhr.setRequestHeader('X-CSRF-Token', $('meta[name="csrf-token"]').attr('content'))},
      success : function(data, textStatus){
        console.log(data);
        console.log(textStatus);
      },
      error : function(XMLHttpRequest, textStatus, errorThrown){
        alert("Oops: "+errorThrown);
      }
    });
  } 

  $('a.rate_btn').click( function() {
    rateProgram($(this).data('url'));
    return false;
  });

</script>